import uuid

from django.conf import settings
from django.db import models


class AgentAlert(models.Model):
    """
    Agent alert model for notifications and actions.
    Stores alerts generated by CrewAI agents.
    """

    SEVERITY_LEVELS = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("critical", "Critical"),
    ]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("acknowledged", "Acknowledged"),
        ("executed", "Executed"),
        ("dismissed", "Dismissed"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="agent_alerts",
    )
    title = models.CharField(max_length=255)
    description = models.TextField()
    severity = models.CharField(max_length=50, choices=SEVERITY_LEVELS)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default="pending")

    # Action payload for function calling
    action_payload = models.JSONField(
        blank=True,
        null=True,
        help_text="Function calling arguments for automated actions",
    )

    # Source reference
    source_type = models.CharField(max_length=50, blank=True, null=True)
    source_id = models.UUIDField(blank=True, null=True)

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    acknowledged_at = models.DateTimeField(blank=True, null=True)
    executed_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "agent_alerts"
        verbose_name = "agent alert"
        verbose_name_plural = "agent alerts"
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.severity.upper()}] {self.title}"
