filebeat.inputs:
- type: filestream
  id: ml-auditor-logs
  enabled: true
  paths:
    - /var/log/ml-auditor/**/*.log
  parsers:
    - ndjson:
        target: ""

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
