# Generated by Django 4.2.17 on 2026-07-23 04:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(help_text='Vector embedding for semantic search (384 dimensions)')),
                ('cluster_category', models.CharField(choices=[('recrutement', 'Recrutement'), ('urgent', 'Urgent'), ('finance', 'Finance'), ('kijiji_deal', 'Kijiji Deal'), ('calendar', 'Calendar'), ('general', 'General')], default='general', max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='data_streams.datastream')),
            ],
            options={
                'verbose_name': 'document chunk',
                'verbose_name_plural': 'document chunks',
                'db_table': 'document_chunks',
                'indexes': [models.Index(fields=['cluster_category'], name='document_ch_cluster_afe9df_idx'), models.Index(fields=['created_at'], name='document_ch_created_bf5d23_idx')],
            },
        ),
    ]
