# Generated by Django 4.2.17 on 2026-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_chunks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="cluster_category",
            field=models.CharField(
                choices=[
                    ("recrutement", "Recrutement"),
                    ("urgent", "Urgent"),
                    ("finance", "Finance"),
                    ("kijiji_deal", "Kijiji Deal"),
                    ("calendar", "Calendar"),
                    ("general", "General"),
                    ("jira", "Jira"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
