# Generated by Django 4.2.17 on 2026-08-04 01:39

import apps.document_chunks.fields
from django.db import migrations, models


def upgrade_embedding_to_vector(apps, schema_editor):
    """Migrate the JSONB embedding column to a real pgvector column.

    Postgres is the production database, so on Postgres this casts the
    serialized JSON array to ``vector(1024)`` and builds an HNSW cosine index
    for ANN search. SQLite (the test database) has no vector type: the field's
    ``db_type`` already reports TEXT there, so nothing needs to change on disk.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")
    schema_editor.execute(
        "ALTER TABLE document_chunks "
        "ALTER COLUMN embedding TYPE vector(1024) "
        "USING embedding::text::vector(1024)"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS document_chunks_embedding_idx "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade_embedding_to_json(apps, schema_editor):
    """Reverse the embedding migration (pgvector -> JSONB)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DROP INDEX IF EXISTS document_chunks_embedding_idx"
    )
    schema_editor.execute(
        "ALTER TABLE document_chunks "
        "ALTER COLUMN embedding TYPE jsonb "
        "USING to_jsonb(embedding::text)::jsonb"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("document_chunks", "0003_alter_documentchunk_cluster_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="cluster_category",
            field=models.CharField(
                choices=[
                    ("recrutement", "Recrutement"),
                    ("urgent", "Urgent"),
                    ("finance", "Finance"),
                    ("kijiji_deal", "Kijiji Deal"),
                    ("calendar", "Calendar"),
                    ("general", "General"),
                    ("jira", "Jira"),
                    ("social", "Social"),
                    ("job_alert", "Job Alert"),
                    ("job_event", "Job Event"),
                    ("networking", "Networking"),
                    ("receipt", "Receipt"),
                    ("security", "Security"),
                    ("newsletter", "Newsletter"),
                    ("project_idea", "Project Idea"),
                    ("job_offer", "Job Offer"),
                    ("job_rejection", "Job Rejection"),
                    ("job_interview", "Job Interview"),
                    ("subscription", "Subscription"),
                    ("shipping", "Shipping"),
                    ("marketing", "Marketing"),
                    ("survey", "Survey"),
                    ("travel", "Travel"),
                    ("meeting", "Meeting"),
                    ("legal", "Legal"),
                    ("document", "Document"),
                ],
                default="general",
                max_length=100,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="documentchunk",
                    name="embedding",
                    field=apps.document_chunks.fields.EmbeddingVectorField(
                        blank=True,
                        dimensions=1024,
                        help_text="pgvector embedding for semantic search (1024 dimensions)",
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    upgrade_embedding_to_vector,
                    downgrade_embedding_to_json,
                ),
            ],
        ),
    ]
