# Generated by Django 4.2.17 on 2026-07-23 04:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("executed", "Executed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "action_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Function calling arguments for automated actions",
                        null=True,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=50, null=True)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "agent alert",
                "verbose_name_plural": "agent alerts",
                "db_table": "agent_alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
