# Generated by Django 4.2.17 on 2026-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_canva_access_token_user_canva_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jira_api_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="jira_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="jira_site_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
