# Generated by Django 4.2.17 on 2026-08-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_mock_data_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jira_oauth_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='jira_oauth_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
