"""
Tool executor — runs function calls from the agent.
Bridges NIM tool calls to actual backend services.
"""

import logging
from typing import Any, Dict

from asgiref.sync import sync_to_async

logger = logging.getLogger(__name__)


class ToolExecutor:
    """
    Executes tool calls from the agent.
    Each tool maps to a backend service or API call.
    """

    def __init__(self, user):
        self.user = user

    async def execute(self, tool_name: str, args: Dict[str, Any]) -> Dict[str, Any]:
        """Route and execute a tool call."""
        handler = getattr(self, f"_exec_{tool_name}", None)
        if handler:
            try:
                return await handler(args)
            except Exception as e:
                logger.error(f"Tool {tool_name} failed: {e}")
                return {"success": False, "error": str(e)}
        else:
            return {"success": False, "error": f"Unknown tool: {tool_name}"}

    # ─── Task tools ──────────────────────────────────────────────────

    async def _exec_create_task(self, args: Dict) -> Dict:
        from apps.workspace.models import Task

        def _create():
            return Task.objects.create(
                user=self.user,
                title=args["title"],
                description=args.get("description", ""),
                status=args.get("status", "todo"),
                priority=args.get("priority", "medium"),
            )
        task = await sync_to_async(_create)()
        return {"success": True, "task_id": str(task.id), "title": task.title}

    # ─── Email tools ─────────────────────────────────────────────────

    async def _exec_send_email(self, args: Dict) -> Dict:
        user = self.user
        if user.email_imap_host and user.email_imap_password:
            from apps.users.services.email_client import EmailClient
            client = EmailClient(
                email_address=user.email,
                password=user.email_imap_password,
                provider=user.email_provider or "custom",
                smtp_host=user.email_smtp_host,
                smtp_port=user.email_smtp_port,
                use_ssl=user.email_use_ssl,
            )
            client.send_message(
                to=args["to"],
                subject=args["subject"],
                body=args["body"],
                cc=args.get("cc"),
            )
            return {"success": True, "to": args["to"], "subject": args["subject"]}
        elif user.google_access_token:
            from apps.users.services import GmailClient
            gmail = GmailClient(user)
            gmail.send_message(to=args["to"], subject=args["subject"], body=args["body"], cc=args.get("cc"))
            return {"success": True, "to": args["to"], "subject": args["subject"]}
        return {"success": False, "error": "No email provider configured"}

    async def _exec_search_email(self, args: Dict) -> Dict:
        user = self.user
        if user.email_imap_host and user.email_imap_password:
            from apps.users.services.email_client import EmailClient
            client = EmailClient(
                email_address=user.email,
                password=user.email_imap_password,
                provider=user.email_provider or "custom",
                imap_host=user.email_imap_host,
                imap_port=user.email_imap_port,
                use_ssl=user.email_use_ssl,
            )
            messages = client.search_messages(
                query=args["query"],
                folder=args.get("folder", "INBOX"),
                limit=10,
            )
            return {"success": True, "messages": messages[:5], "count": len(messages)}
        return {"success": False, "error": "No email provider configured"}

    async def _exec_draft_email_reply(self, args: Dict) -> Dict:
        # Draft is generated by the agent, this just stores/returns it
        return {
            "success": True,
            "draft": {
                "to": args.get("original_from", ""),
                "subject": f"Re: {args.get('original_subject', '')}",
                "body": args.get("draft_body", ""),
                "tone": args.get("tone", "professional"),
            },
        }

    # ─── Calendar tools ──────────────────────────────────────────────

    async def _exec_create_calendar_event(self, args: Dict) -> Dict:
        user = self.user
        if user.google_access_token:
            from apps.users.services import CalendarClient
            from datetime import datetime
            cal = CalendarClient(user)
            event = cal.create_event(
                summary=args["summary"],
                start_time=datetime.fromisoformat(args["start_time"]),
                end_time=datetime.fromisoformat(args["end_time"]),
                description=args.get("description"),
                location=args.get("location"),
            )
            return {"success": True, "event_id": event.get("id")}
        return {"success": False, "error": "Google Calendar not connected"}

    # ─── Kijiji tools ────────────────────────────────────────────────

    async def _exec_search_kijiji(self, args: Dict) -> Dict:
        from apps.users.services import KijijiScraperService
        scraper = KijijiScraperService(user=self.user)
        listings = scraper.search_listings(
            query=args["query"],
            location=args.get("location"),
            min_price=args.get("min_price"),
            max_price=args.get("max_price"),
        )
        return {"success": True, "listings": listings[:5], "count": len(listings)}

    # ─── Financial tools ─────────────────────────────────────────────

    async def _exec_analyze_transactions(self, args: Dict) -> Dict:
        user = self.user
        if user.plaid_access_token:
            from apps.users.services import PlaidClient
            from datetime import datetime, timedelta
            plaid = PlaidClient(user)
            days = args.get("days", 30)
            end = datetime.now()
            start = end - timedelta(days=days)
            transactions = plaid.get_transactions(start_date=start, end_date=end)
            # Basic analysis
            total_spent = sum(t.get("amount", 0) for t in transactions)
            categories = {}
            for tx in transactions:
                cat = tx.get("category", ["Other"])[0] if tx.get("category") else "Other"
                categories[cat] = categories.get(cat, 0) + tx.get("amount", 0)
            return {
                "success": True,
                "total_transactions": len(transactions),
                "total_spent": round(total_spent, 2),
                "by_category": categories,
            }
        return {"success": False, "error": "Plaid not connected"}

    # ─── Canva tools ─────────────────────────────────────────────────

    async def _exec_canva_competitor_monitor(self, args: Dict) -> Dict:
        user = self.user
        if user.canva_access_token:
            from apps.users.services.canva_client import CanvaClient
            client = CanvaClient(user.canva_access_token)
            result = client.track_competitor_keywords(keywords=args.get("keywords", []))
            return {"success": True, **result}
        return {"success": False, "error": "Canva not connected"}
