# Generated by Django 4.2.17 on 2026-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["user", "start_time"], name="workspace_c_user_id_53843d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["feed", "published_at"], name="workspace_n_feed_id_586007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["feed", "is_read"], name="workspace_n_feed_id_595e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status"], name="workspace_t_user_id_509601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "priority"], name="workspace_t_user_id_e74814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "due_date"], name="workspace_t_user_id_32486a_idx"
            ),
        ),
    ]
