# Generated by Django 4.2.17 on 2026-07-28 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0002_calendarevent_workspace_c_user_id_53843d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("book_chapter", "Book Chapter"),
                            ("presentation", "Presentation"),
                            ("article", "Article"),
                        ],
                        default="note",
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "format"], name="workspace_n_user_id_1d0910_idx"
                    ),
                    models.Index(
                        fields=["user", "is_pinned"],
                        name="workspace_n_user_id_023d8f_idx",
                    ),
                ],
            },
        ),
    ]
