# Generated by Django 4.2.17 on 2026-08-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
