# Generated by Django 4.2.17 on 2026-07-23 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('plaid', 'Plaid (Banking)'), ('kijiji', 'Kijiji')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='active', max_length=16)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('items_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('items_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
