# Generated by Django 4.2.17 on 2026-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_llmconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="service",
            field=models.CharField(
                choices=[
                    ("gmail", "Gmail"),
                    ("google_calendar", "Google Calendar"),
                    ("plaid", "Plaid (Banking)"),
                    ("kijiji", "Kijiji"),
                    ("jira", "Jira"),
                ],
                max_length=32,
            ),
        ),
    ]
