# Generated by Django 4.2.17 on 2026-08-22 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0005_alter_llmconfiguration_providers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrationconnection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='account_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for this account (e.g. email address or bank name).', max_length=255),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='service',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('plaid', 'Plaid (Banking)'), ('kijiji', 'Kijiji'), ('jira', 'Jira'), ('email', 'Email (IMAP)')], max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconnection',
            unique_together={('user', 'service', 'account_label')},
        ),
    ]
