# Generated by Django 4.2.17 on 2026-08-30 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0007_migrate_user_tokens_to_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('plaid', 'Plaid'), ('gmail', 'Gmail / Google API'), ('google_calendar', 'Google Calendar'), ('canva', 'Canva'), ('jira', 'Jira'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('nvidia', 'NVIDIA NIM'), ('custom', 'Custom API')], max_length=32)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable label for this API key set.', max_length=255)),
                ('api_key', models.TextField(blank=True, default='')),
                ('api_secret', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='unknown', max_length=16)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='integrations.apikeyintegration')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='integrations.integrationconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
