# Generated by Django 4.2.17 on 2026-07-23 04:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("kijiji", "Kijiji"),
                            ("plaid", "Plaid"),
                            ("google_calendar", "Google Calendar"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "data stream",
                "verbose_name_plural": "data streams",
                "db_table": "data_streams",
                "ordering": ["-created_at"],
            },
        ),
    ]
