# Generated by Django 4.2.17 on 2026-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_streams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datastream",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("gmail", "Gmail"),
                    ("kijiji", "Kijiji"),
                    ("plaid", "Plaid"),
                    ("google_calendar", "Google Calendar"),
                    ("manual", "Manual Entry"),
                    ("jira", "Jira"),
                ],
                max_length=50,
            ),
        ),
    ]
